# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{xrcov}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["KAZUu"]
  s.date = %q{2010-09-07}
  s.description = %q{coverqage tool for ruby 1.9.x which supports C0, C1 and C2}
  s.email = %q{exkazuu@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/xrcov.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/xrcov_spec.rb"
  ]
  s.homepage = %q{http://github.com/exKAZUu/xrcov}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{coverqage tool for ruby 1.9.x}
  s.test_files = [
    "spec/branchcov_spec.rb",
     "spec/covelemgrp_spec.rb",
     "spec/evalcov_spec.rb",
     "spec/fixture/sample.rb",
     "spec/fixture/sample_spec.rb",
     "spec/spec_helper.rb",
     "spec/stmtcov_spec.rb",
     "spec/xrcov_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

